enum ViewState {
  auth,
  home,
  newRequest,
  tracking,
  payment,
  profile,
  agentDashboard,
  agentSubscription,
  agentCommission,
  agentCommunication,
  operatorDashboard,
  operatorAssignment,
  operatorMediation,
}
